do_forecast_job:
  every: 120m
  class: ForecastWorker
  args:
  description: updates all area weather every 120 minutes

do_instagram_job:
  every: 120m
  class: InstagramWorker
  args:
  description: updates instagrams 120 minutes
